Update instruction to wait after each step
skills/review-pull-requests pull request #5
Opened 2022-05-27 09:39 UTC by georgebrock

### Why:

Training new users to refresh after each action seems like an anti-pattern: these actions should apply more or less immediately, and there shouldn't be any need to refresh the page in between (if there is please let us – the PRs team – know so we can fix it!)

### What's being changed:

Removing the “wait about 20 seconds and then refresh the page” instruction from each step.

### Check off the following:

- [ ] ~~For workflow changes, I have verified the Actions workflows function as expected.~~
- [x] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2022-06-09 21:37 UTC, heiskr commented on README.md
> -1. Wait about 20 seconds then refresh this page for the next step.
@dihydroJenoxide Updated the copy in https://github.com/skills/hello-github-actions to this to clarify the instruction is meant for the instructions page, not the pull request.

> Wait about 20 seconds for actions to run, then refresh this page (the one you're following instructions from) and an action will automatically close this step and open the next one.

2022-06-09 23:15 UTC, dihydroJenoxide requested changes
I updated all the instances where you deleted the instructions to wait with updated language to reflect the waiting is for GitHub Actions and the instruction page instead of for the feature. 

If you'll accept those changes, or discuss further in Slack, then we can get this approved and merged! 

Feel free to open up a similar PR for the other course your team is concerned about and we'll get it approved. If you don't, [we have an issue](https://github.com/github/skills/issues/58) to update this language for all the courses and we'll get it done. 

cc @mntlty @danhodos

2022-06-09 23:15 UTC, dihydroJenoxide commented on README.md
>  1. Under **Reviewers** on the right side of the screen, add yourself as a reviewer.
```suggestion
1. Under **Reviewers** on the right side of the screen, add yourself as a reviewer.

Next, wait about 20 seconds for actions to run, then refresh this course's README (the one you're following instructions from) and a [GitHub Action](https://docs.github.com/en/actions) will automatically close this step and open the next one.
```

2022-06-09 23:15 UTC, dihydroJenoxide commented on README.md
>  1. Click **Submit review**.
```suggestion
1. Click **Submit review**.

Next, wait about 20 seconds for actions to run, then refresh this course's README (the one you're following instructions from) and a [GitHub Action](https://docs.github.com/en/actions) will automatically close this step and open the next one.
```

2022-06-09 23:15 UTC, dihydroJenoxide commented on README.md
>  1. Click **Add a single comment**.
```suggestion
1. Click **Add a single comment**.

Next, wait about 20 seconds for actions to run, then refresh this course's README (the one you're following instructions from) and a [GitHub Action](https://docs.github.com/en/actions) will automatically close this step and open the next one.
```

2022-06-09 23:15 UTC, dihydroJenoxide commented on README.md
>  1. Click **Commit changes**.
```suggestion
1. Click **Commit changes**.

Next, wait about 20 seconds for actions to run, then refresh this course's README (the one you're following instructions from) and a [GitHub Action](https://docs.github.com/en/actions) will automatically close this step and open the next one.
```

2022-06-09 23:15 UTC, dihydroJenoxide commented on README.md
>  1. Delete the branch `update-game` (optional).
```suggestion
1. Delete the branch `update-game` (optional).

Next, wait about 20 seconds for actions to run, then refresh this course's README (the one you're following instructions from) and a [GitHub Action](https://docs.github.com/en/actions) will automatically close this step and open the next one.
```

2022-06-10 16:28 UTC, heiskr approved these changes

2022-06-13 15:35 UTC, merged